version: '3'

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Ast/UTC
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - /docker/crafty-4/backups:/crafty/backups
        - /docker/crafty-4/logs:/crafty/logs
        - /docker/crafty-4/servers:/crafty/servers
        - /docker/crafty-4/config:/crafty/app/config
        - /docker/crafty-4/import:/crafty/import