services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
      - proxy

    ports:
      - "80:80"
      - "443:443"

    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/traefik/traefik.yaml:/traefik.yaml:ro
      - /docker/traefik/acme.json:/acme.json
      - /docker/traefik/config.yaml:/config.yaml:ro
      - /docker/traefik/logs:/var/log/traefik

    labels:
      - "traefik.enable=true"
      # HTTP router: redirect all HTTP to HTTPS
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.rynewood.ca`)"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      # HTTPS router: secure dashboard
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.rynewood.ca`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      # Basic authentication for dashboard
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDS}"
      # X-Forwrded-Proto header for websockets and security
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=rynewood.ca"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.rynewood.ca"
      

networks:
  proxy:
    external: true
    
